apiVersion: apps/v1beta1
kind: ReplicationController
metadata:
  name: nginx-web
  namespace: my-kube
spec:
  replicas: 4
  selector:
    app: nginx
  template:
    metadata:
      name: nginx-2
      labels:
        app: nginx-2
    spec:
      containers:
      - name: my-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        
        
